name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
  runs-on: ubuntu-latest
  steps:
    - name: Simple JS Action
      id: greet
      user: MichalMlynarski/github-action-test@master
      with: 
        who-to-greet: Tom
    - name: Log Greeting Time
      run: echo "${{ steps.greet.outpust.time }}"    
