name: Actions Workflow

on: 
  schedule:
    #- cron: "0/5 * * * *"
    #- cron: "0/6 * * * *"
    - cron: "* * * * *"
  #push:
  pull_request:
    types: [closed, assigned, opend, reopend]
    

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List File
        run: |
          pwd
          ls -s
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token}}"
          #git clone git@github:$GITHUB_REPOSITORY
          #git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v3.0.2   
      - name: List File After Checkout  
        run: |
          pwd
          ls -s  
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: Tom & Jerry
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"    
