name: Shell Comands

on: [push]

jobs:
  run-shell-commend: 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        if: faliure()
        run: |
          node -v
          npm -v
      - name: python Commands  
        run: |
          import platform
          print(platform.processor())
        shell: python  
  run-windows-commends:
    runs-on: windows-latest
    needs: ["run-shell-commend"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash  
